apiVersion: apps/v1
kind: Deployment
metadata:
  name: mop-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: malauryd/mop_authentication
        env:
          - name: PORT
            value: '8080'
          - name: MONGO_URL
            value: 'mongodb://mongodb-service:27017/MOPv2'
        ports:
        - containerPort: 8080
        resources:
          limits:
           memory: "64Mi"
           cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authentication
  name: authentication-service
spec:
  ports:
  - name: 'http'
    port: 80
    targetPort: 8080
  selector:
    app: authentication
  type: NodePort
