apiVersion: apps/v1
kind: Deployment
metadata:
  name: mop-deezerindexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deezerindexer
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: deezerindexer
    spec:
      containers:
      - name: deezerindexer
        image: malauryd/mop_deezerindexer
        env:
          - name: MONGO_URL
            value: 'mongodb://mongodb-service:27017/MOPv2'
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deeezerindexer
  name: deeezerindexer-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: deezerindexer
  type: ClusterIP