apiVersion: apps/v1
kind: Deployment
metadata:
  name: mop-musicfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicfrontend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: musicfrontend
    spec:
      containers:
      - name: musicfrontend
        image: malauryd/mop_musicfrontend
        env:
          - name: PORT
            value: '8080'
        ports:
        - containerPort: 8080
        resources:
          limits:
           memory: "64Mi"
           cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: musicfrontend
  name: musicfrontend-service
spec:
  ports:
  - name: 'http'
    port: 80
    targetPort: 8080
  selector:
    app: musicfrontend
  type: NodePort
